### ISSUE TITLE
IE bug na resize van medium naar small, nav en article onder elkaar ipv naast elkaar

### ISSUE THREAD

**Issue by JasperLagemaat** [RobVermeer/tenista#44]

**Comment by RobVermeer** [comment]
@JasperLagemaat  kan je deze uitleggen, ik zie niet waar dit fout gaat en kan ook niet in IE zien dat er iets anders gebeurt dan in Chrome.

**Comment by RobVermeer** [comment]
@JasperLagemaat Is dit nog steeds het geval?

**Comment by JasperLagemaat** [comment]
Het is nog steeds het geval, maar zo'n klein probleem dat het nu niet nodig is er aandacht aan te besteden.






Van: Rob Vermeer
Verzonden: ‎maandag‎ ‎26‎ ‎januari‎ ‎2015 ‎19‎:‎27
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





@JasperLagemaat Is dit nog steeds het geval?

**Comment by JasperLagemaat** [comment]
![schermopname 193](https://cloud.githubusercontent.com/assets/10269668/5906612/55904424-a599-11e4-8bc6-0defe16baa81.png)
