### ISSUE TITLE
Carousel vaste hoogte

### ISSUE THREAD

**Issue by JasperLagemaat** [RobVermeer/tenista#60]
Ik wil dat de carousel een vaste hoogte heeft en niet tijdens de animatie verandert omdat verschillende afbeeldingen een andere verhouding hebben. Ik heb al een max-height toegevoegd, maar dit helpt nog niet bij de mobiele versie.

**Comment by RobVermeer** [comment]
Zoals ik het nu zie ziet het er ook goed uit, deze close ik. Mocht je toch nog wat hebben, kan je een nieuwe todo aanmaken =)
