### ISSUE TITLE
Desktop header img als bg ipv img

### ISSUE THREAD

**Issue by JasperLagemaat** [RobVermeer/tenista#66]
@RobVermeer De desktop header afbeelding wordt als afbeelding geladen, dus ook in de mobiele versie en is best een groot bestand. Deze ook maar beter als achtergrond van een div zetten vanaf bepaalde viewport?

**Comment by RobVermeer** [comment]
Ja is een goede, had nog even opgezocht, dacht dat tegenwoordig dat niet meer zo was, maar ik lijk me daarin te vergissen.

Wel irritant dat dat zo is, want ik vind een bg image niet zo'n mooie oplossing, maar als het scheelt is het een goede keuze.
