### ISSUE TITLE
Inschrijfformulier

### ISSUE THREAD

**Issue by JasperLagemaat** [RobVermeer/tenista#68]
Ik heb een begin gemaakt aan het inschrijfformulier, maar kan het verder niet werkend krijgen. Ik hoop dat jij hier voor kan zorgen.

**Comment by RobVermeer** [comment]
Hopeloos als je lokaal geen mail server hebt ingesteld =( Maar zit erin!

Ik heb jou @JasperLagemaat emailadres ingesteld op de site, dus je kan testen en dan krijg je, als het goed is =), een mail met info en afbeelding.

Vb. http://share.vermeertech.nl/1iWlL (paarse is quoted tekst, dat doet Gmail =)
