### ISSUE TITLE
Fotoalbums

### ISSUE THREAD

**Issue by JasperLagemaat** [RobVermeer/tenista#73]
@RobVermeer 
De bedoeling van de fotopagina:
- startpagina waarop ingelogd kan worden, met universeel wachtwoord.
Voor het gemak is het denk ik beter om alle foto's af te schermen. Als we toch besluiten een selectie wel direct zichtbaar te willen maken, is dit dan eenvoudig te veranderen?
Op deze pagina ook een overzicht van de te kiezen albums, liefst met een thumbnail om op te klikken. (na inloggen keer je dus terug naar zelfde scherm zonder inlogmogelijkheid, maar met de tekst dat je ingelogd bent.)
- ik heb albums samengesteld van 30-60 foto's. Ik weet niet wat de mogelijkheden zijn qua inladen, maar ideaal zou zijn als alle foto's binnen een bepaalde map herkend worden als één album en automatisch geladen worden.
- wanneer op album geklikt, korte beschrijving evenement en laadt eerste 15 foto's per album. Button onderaan om meer foto's te laden. 
- lightbox om vergroot af te beelden en snelle navigatie door foto's.

Hier een screenshot van mijn ontwerp: 
![schermopname 178](https://cloud.githubusercontent.com/assets/10269668/5695606/71e3281a-99ac-11e4-9a07-8dec062dfd33.png)

**Comment by RobVermeer** [comment]
Ik heb hier even over nagedacht, ik bel je morgen even om het te bespreken (als ik het niet vergeet =)

**Comment by RobVermeer** [comment]
@JasperLagemaat http://tenista.robvermeer.nl/fotos/

Ik heb al een album aangemaakt zodat je kan zien hoe, als je er niet uit komt, of veranderingen wilt zien, let me know.

http://share.vermeertech.nl/1hbym

Ps.wchtwoord voor de test is tenista

Ik sluit deze, als er iets moet gebeuren zie ik de nieuwe issues tegemoet.

Btw als je nog cleanup moet doen (in CSS staat nog iets van fotos zag ik), doe dat dan even =) Laten we het lekker netjes houden

**Comment by JasperLagemaat** [comment]
Ik zag dat je bezig was en had het wachtwoord al geraden voordat je het stuurde 😉

Ziet er goed uit! Ik kan nu zelf een album toevoegen om het uit te proberen? 

De style die ik voor foto's had toegevoegd was voor album thumbnails op de foto-openingspagina. Aan de telefoon had je gezegd dat we een featured foto als soort van albumhoes konden zetten op deze pagina. Is dat nog mogelijk? Op het moment dat een album dan geopend is zie je een lijst met de albums als page-nav links zoals nu het geval is.






Van: Rob Vermeer
Verzonden: ‎maandag‎ ‎26‎ ‎januari‎ ‎2015 ‎21‎:‎36
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





@JasperLagemaat http://tenista.robvermeer.nl/fotos/

Ik heb al een album aangemaakt zodat je kan zien hoe, als je er niet uit komt, of veranderingen wilt zien, let me know.

http://share.vermeertech.nl/1hbym

Ps.wchtwoord voor de test is tenista

Ik sluit deze, als er iets moet gebeuren zie ik de nieuwe issues tegemoet.

Btw als je nog cleanup moet doen (in CSS staat nog iets van fotos zag ik), doe dat dan even =) Laten we het lekker netjes houden

**Comment by RobVermeer** [comment]
Je kan zeker beginnen met toevoegen!

Ik dacht dat we uiteindelijk besloten hadden om alleen via de sidebar te navigeren, maar misschien vergis ik me wel :)

Dus album covers op de overzichts pagina en op de album pagina zelf sidebar navigatie?

**Comment by JasperLagemaat** [comment]
Ja dat was mijn idee. 

Ik heb 2 afbeeldingen toegevoegd aan het eerste album maar ik zie dat de beer-foto daardoor een beetje op een rare plek is terechtgekomen.






Van: Rob Vermeer
Verzonden: ‎maandag‎ ‎26‎ ‎januari‎ ‎2015 ‎22‎:‎14
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





Je kan zeker beginnen met toevoegen!

Ik dacht dat we uiteindelijk besloten hadden om alleen via de sidebar te navigeren, maar misschien vergis ik me wel :)

Dus album covers op de overzichts pagina en op de album pagina zelf sidebar navigatie?

**Comment by RobVermeer** [comment]
Ah dat komt omdat het plaatje niet zo groot is, maar daar weet ik wel een oplossing voor, fix ik zo. Dus je kan gewoon blijven testen/uploaden etc.

**Comment by JasperLagemaat** [comment]
Ik ga morgen na tentamen albums toevoegen ;)

Oh en nog een vraagje: wanneer een album geopend wordt, worden dan meteen alle grote afbeeldingen geladen of eerst alleen kleine versies tot je de lightbox opent?






Van: Rob Vermeer
Verzonden: ‎maandag‎ ‎26‎ ‎januari‎ ‎2015 ‎22‎:‎22
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





Ah dat komt omdat het plaatje niet zo groot is, maar daar weet ik wel een oplossing voor, fix ik zo. Dus je kan gewoon blijven testen/uploaden etc.

**Comment by RobVermeer** [comment]
Dat laatste

**Comment by JasperLagemaat** [comment]
Top! En ik wil je nog vragen om te maken dat wanneer een nieuw album wordt toegevoegd, deze bovenaan de lijst verschijnt ipv onderaan. 






Van: Rob Vermeer
Verzonden: ‎maandag‎ ‎26‎ ‎januari‎ ‎2015 ‎22‎:‎27
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





Dat laatste

**Comment by RobVermeer** [comment]
http://tenista.robvermeer.nl/fotos/

Overview aangepast naar thumbs. Order aangepast naar date.
