### ISSUE TITLE
Back-up oude site

### ISSUE THREAD

**Issue by RobVermeer** [RobVermeer/tenista#86]
Het lijkt me handig als je even een back-up maakt van de oude site. (via FTP content downloaden en via PhpMyAdmin DB downloaden).

Als je dat hebt gedaan ga ik het live zetten, dus laat even weten when done, of als je hulp nodig hebt.

**Comment by RobVermeer** [comment]
Ik heb backup gemaakt. Zal ik met training laptop meenemen zodat het kan worden overgezet naar jou?

**Comment by JasperLagemaat** [comment]
Ja is goed. Genoeg als ik een USB meeneem?






Van: Rob Vermeer
Verzonden: ‎dinsdag‎ ‎27‎ ‎januari‎ ‎2015 ‎23‎:‎27
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





Ik heb backup gemaakt. Zal ik met training laptop meenemen zodat het kan worden overgezet naar jou?

**Comment by RobVermeer** [comment]
Yes als je ongeveer 600MB vrij hebt moet dat lukken
