### ISSUE TITLE
Pinkstertoernooi banenveiling op website

### ISSUE THREAD

**Issue by JasperLagemaat** [RobVermeer/tenista#89]

**Comment by RobVermeer** [comment]
Leuk idee, dat als eerste =)

Wat ik me af vraag is of je zelf al een idee hebt hoe je het eruit wil laten zien?

Ik heb even een opzetje gemaakt:
![banenveiling](https://cloud.githubusercontent.com/assets/1416116/7171904/3b2c7e2a-e3df-11e4-9eaf-ecbb71ffab1a.png)

Zoiets lijkt me simpel in elkaar te zetten en ook te designen.

De vraag is dan natuurlijk ook hoe om te gaan met valse data e.d. Oftewel er moet dan ook een back-end voor zijn.

Lijkt me wel doable, maar zal toch wat meer input moeten om het volledig te kunnen maken.

**Comment by RobVermeer** [comment]
Weet niet of je hier een notificatie van krijgt dus bij deze nog even een @JasperLagemaat

**Comment by JasperLagemaat** [comment]
Ik denk dat een opzetje zoals je gemaakt hebt goed is, ziet er netjes uit! Misschien een staafdiagram van alle banen naast elkaar in een overzicht als eerste tabje. Het verloop per baan vind ik ook een leuk idee.

Valse boden zaten wij ook een beetje mee. Voordeel aan facebook was dat je van iedereen die bood, zijn profiel kon bekijken en eenvoudig contact op kon nemen. Is het mogelijk om een veiling via de site ook aan facebook-profielen te verbinden? Mensen kunnen eventueel kiezen of ze mailadres ingeven of facebook. 

Kan je hier wat mee of heb je nog meer input nodig?


Groet,

Jasper






Van: Rob Vermeer
Verzonden: ‎donderdag‎ ‎16‎ ‎april‎ ‎2015 ‎02‎:‎24
Aan: RobVermeer/tenista
CC: Jasper van de Lagemaat





Leuk idee, dat als eerste =)

Wat ik me af vraag is of je zelf al een idee hebt hoe je het eruit wil laten zien?

Ik heb even een opzetje gemaakt:
 banenveiling 

Zoiets lijkt me simpel in elkaar te zetten en ook te designen.

De vraag is dan natuurlijk ook hoe om te gaan met valse data e.d. Oftewel er moet dan ook een back-end voor zijn.

Lijkt me wel doable, maar zal toch wat meer input moeten om het volledig te kunnen maken.

**Comment by RobVermeer** [comment]
@JasperLagemaat Ik heb het in elkaar geknutseld, je kan het checken @ http://tenista.robvermeer.nl/banenveiling/

Check ook de back-end @ 
http://tenista.robvermeer.nl/wp-admin/edit.php?post_type=auction
